MQTT_BROKER = "MQTT_BROKER"
MQTT_PORT = "MQTT_PORT"
MQTT_KEEPALIVE = "MQTT_KEEPALIVE"
MQTT_QOS = "MQTT_QOS"
MQTT_TOPICS = "MQTT_TOPICS"
MQTT_TOPICS_BLACKLIST = "MQTT_TOPICS_BLACKLIST"
MQTT_TOPIC_SEPARATOR = "$$$$"

SQL_HOST = "SQL_HOST"
SQL_PORT = "SQL_PORT"
SQL_DATABASE = "SQL_DATABASE"
SQL_USER = "SQL_USER"
SQL_PASSWORD = "SQL_PASSWORD"
SQL_CHARSET = "SQL_CHARSET"

DEFAULT_MQTT_BROKER = "127.0.0.1"
DEFAULT_MQTT_PORT = 1883
DEFAULT_MQTT_KEEPALIVE = 60
DEFAULT_MQTT_QOS = 0
DEFAULT_MQTT_TOPICS = "#"

DEFAULT_SQL_HOST = "127.0.0.1"
DEFAULT_SQL_PORT = 3306
DEFAULT_SQL_DATABASE = "mqtt"
DEFAULT_SQL_CHARSET = "utf8mb4"
